INSERT INTO Gender(value)
VALUES('Male');
INSERT INTO Gender(value)
VALUES('Female');
INSERT INTO Gender(value)
VALUES('Other');

INSERT INTO Tournament(TEAM_SIZE_REQUIRED, DATE, TIME, NAME, PRIZE, GAME, INFO )
VALUES('2','2021-01-05','00:30','Tour1','10','PUBG','CODMW');
INSERT INTO Tournament(TEAM_SIZE_REQUIRED, DATE, TIME, NAME, PRIZE, GAME, INFO )
VALUES('3','2021-01-04','12:30','Tour2','20','COD','PUBG');
INSERT INTO Tournament(TEAM_SIZE_REQUIRED, DATE, TIME, NAME, PRIZE, GAME, INFO )
VALUES('2','2021-01-03','00:30','Tour3','30','PUBG','CODWZ');
INSERT INTO Tournament(TEAM_SIZE_REQUIRED, DATE, TIME, NAME, PRIZE, GAME, INFO )
VALUES('1','2021-01-02','12:30','Tour4','40','COD','RL');
INSERT INTO Tournament(TEAM_SIZE_REQUIRED, DATE, TIME, NAME, PRIZE, GAME, INFO )
VALUES('2','2021-01-01','00:30','Tour5','50','PUBG','LOL');
INSERT INTO Tournament(TEAM_SIZE_REQUIRED, DATE, TIME, NAME, PRIZE, GAME, INFO )
VALUES('4','2021-01-06','12:30','Tour6','60','COD','Apex');
INSERT INTO Tournament(TEAM_SIZE_REQUIRED, DATE, TIME, NAME, PRIZE, GAME, INFO )
VALUES('3','2021-01-07','00:30','Tour7','70','PUBG','LOL');
INSERT INTO Tournament(TEAM_SIZE_REQUIRED, DATE, TIME, NAME, PRIZE, GAME, INFO )
VALUES('3','2021-01-08','12:30','Tour8','80','COD','Apex');


INSERT INTO Team(NAME, SIZE, TOURNAMENT_ID )
VALUES('Team1','2','5');
INSERT INTO Team(NAME, SIZE, TOURNAMENT_ID )
VALUES('Team2','2','5');
INSERT INTO Team(NAME, SIZE, TOURNAMENT_ID )
VALUES('Team3','2','5');
INSERT INTO Team(NAME, SIZE, TOURNAMENT_ID )
VALUES('Team4','2','5');
INSERT INTO Team(NAME, SIZE, TOURNAMENT_ID )
VALUES('Team5','2','5');
INSERT INTO Team(NAME, SIZE, TOURNAMENT_ID )
VALUES('Team6','2','5');
INSERT INTO Team(NAME, SIZE, TOURNAMENT_ID )
VALUES('Team7','2','5');
INSERT INTO Team(NAME, SIZE, TOURNAMENT_ID )
VALUES('Team8','2','5');
INSERT INTO Team(NAME, SIZE, TOURNAMENT_ID )
VALUES('Team9','2','5');
INSERT INTO Team(NAME, SIZE, TOURNAMENT_ID )
VALUES('Team10','2','5');

INSERT INTO Team(NAME, SIZE, TOURNAMENT_ID )
VALUES('Team11','1','4');
INSERT INTO Team(NAME, SIZE, TOURNAMENT_ID )
VALUES('Team12','1','4');
INSERT INTO Team(NAME, SIZE, TOURNAMENT_ID )
VALUES('Team13','1','4');
INSERT INTO Team(NAME, SIZE, TOURNAMENT_ID )
VALUES('Team14','1','4');
INSERT INTO Team(NAME, SIZE, TOURNAMENT_ID )
VALUES('Team15','1','4');
INSERT INTO Team(NAME, SIZE, TOURNAMENT_ID )
VALUES('Team16','1','4');
INSERT INTO Team(NAME, SIZE, TOURNAMENT_ID )
VALUES('Team17','1','4');
INSERT INTO Team(NAME, SIZE, TOURNAMENT_ID )
VALUES('Team18','1','4');